---
- hosts: all
  gather_facts: false
  tasks:
    - name: Set authorized key for user someuser copying it from current user
      authorized_key:
        user: someuser
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
